apiVersion: batch/v1
kind: CronJob
metadata:
  name: yukibot-cronjob
  namespace: yukibot
spec:
  schedule: "0 0-12 * * *" # Every hour from 09:00 to 21:00 JST
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: yukibot
            image: us-west1-docker.pkg.dev/yukibot-0725/yukibot/yukibot:latest
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never
